local MODE = MODE

zb = zb or {}
zb.Points = zb.Points or {}

zb.Points.HMCD_WITPROTECT_POLICE = zb.Points.HMCD_WITPROTECT_POLICE or {}
zb.Points.HMCD_WITPROTECT_POLICE.Color = Color(40, 120, 255)
zb.Points.HMCD_WITPROTECT_POLICE.Name = "HMCD_WITPROTECT_POLICE"

zb.Points.HMCD_WITPROTECT_WITNESS = zb.Points.HMCD_WITPROTECT_WITNESS or {}
zb.Points.HMCD_WITPROTECT_WITNESS.Color = Color(255, 210, 70)
zb.Points.HMCD_WITPROTECT_WITNESS.Name = "HMCD_WITPROTECT_WITNESS"

zb.Points.HMCD_WITPROTECT_MAFIA = zb.Points.HMCD_WITPROTECT_MAFIA or {}
zb.Points.HMCD_WITPROTECT_MAFIA.Color = Color(180, 40, 40)
zb.Points.HMCD_WITPROTECT_MAFIA.Name = "HMCD_WITPROTECT_MAFIA"
